"""extend_products_for_identity

Revision ID: 9414599a87eb
Revises: 0c78fb578dd2
Create Date: 2026-07-07 20:02:18.190070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9414599a87eb'
down_revision: Union[str, None] = '0c78fb578dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variants', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('detected_niche', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_refs', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_refs')
        batch_op.drop_column('detected_niche')
        batch_op.drop_column('variants')

    # ### end Alembic commands ###
